export const hoverPopupLayers = [
	'Creeks',
	'HomeSales',
	'MSPD'
]
export const clickPopupLayers = [
	'Results',
	'modified_Results',
	'Unmatched',
	'OrigOwner',
	'SewerCCN',
	'WaterCCN',
	'Cities',
	'SchoolZones',
	'Projects',
	'PerformingProjects',
	'Government',
	'ETJ',
	'UtilityDistricts',
	'Counties',
	'HighPlains',
	'Northwest',
	'Metroplex',
	'UpperEast',
	'SouthEast',
	'GulfCoast',
	'Central',
	'Alamo',
	'West',
	'RioGrande',
	'South',
	'Ownerships',
	'Listings',
	'modified_Listings',
	'Sales',
	'modified_Sales',
	'RecentSales',
	'modified_RecentSales',
	'Pending',
	'modified_Pending',
	'PCC_inactive',
	'modified_PCC_inactive'
]
export const layerOrderBefore = [
	'Listings',
	'Pending',
	'Listings',
	'Sales',
	'RecentSales',
	'PerformingProjects',
	'Projects',
	'Ownerships',
	'SchoolZones',
	'Cities',
	'ETJ',
	'UtilityDistricts',
	'OpportunityZones',
	'Railroads',
	'PowerLines',
	'Counties',
	'Water',
	'WaterExtent',
	'WasteWater',
	'WasteWaterExtent',
	'WaterCCN',
	'SewerCCN',
	'Unacast',
	'Traffic',
	'Government',
	'tx_travis',
	'FEMA100yr',
	'FEMA500yr',
	'Creeks',
	'CWQ',
	'ContourLines',
	'Slope',
	'Pipelines',
	'Wells',
	'OGWells',
	'EdwardsRecharge',
	'EdwardsContributing',
	'GCWH',
	'Perennial',
	'Intermittent',
	'Waterbody',
	'PCC_inactive',
	'Whiteout',
];

const getToday = () =>{
	var today = new Date();
	var dd = String(today.getDate()).padStart(2, '0');
	var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
	var yyyy = today.getFullYear() - 2;
	return yyyy + '-' + mm + '-' + dd;
}

export const defaultFilterData = {
	RecentSales: '2019-01-24',
    MSPD: '2021-10',
    Ownerships: [100, 999999999],
    HexMigrationInflow: [75, 100],
    PPAIndex: 2021,
    LandCover: 2019,
    LandCoverChange: [2016,2019],
}
