/*---------------
    OWNERSHIPS
---------------*/
export const ownershipSources = {
  "Ownerships-HighPlains": [
    // "tx_donley_ownerships", error
    "tx_dickens_ownerships",
    // "tx_garza_ownerships", error
    "tx_cochran_ownerships",
    "tx_hansford_ownerships",
    "tx_crosby_ownerships",
    "tx_moore_ownerships",
    "tx_roberts_ownerships",
    "tx_dallam_ownerships",
    "tx_lamb_ownerships",
    "tx_lubbock_ownerships",
    "tx_potter_ownerships",
    "tx_motley_ownerships",
    "tx_floyd_ownerships",
    "tx_hale_ownerships",
    "tx_yoakum_ownerships",
    "tx_castro_ownerships",
    "tx_carson_ownerships",
    "tx_parmer_ownerships",
    "tx_king_ownerships",
    "tx_bailey_ownerships",
    "tx_hall_ownerships",
    "tx_wheeler_ownerships",
    "tx_collingsworth_ownerships",
    "tx_sherman_ownerships",
    "tx_lynn_ownerships",
    "tx_armstrong_ownerships",
    "tx_childress_ownerships",
    "tx_deaf-smith_ownerships",
    "tx_hartley_ownerships",
    "tx_briscoe_ownerships",
    "tx_lipscomb_ownerships",
    "tx_oldham_ownerships",
    "tx_randall_ownerships",
    "tx_swisher_ownerships",
    "tx_gray_ownerships",
    "tx_hockley_ownerships",
    // "tx_hutchinson_ownerships", error
    "tx_terry_ownerships",
    "tx_hemphill_ownerships",
    "tx_ochiltree_ownerships",
  ],
  "Ownerships-Northwest": [
    "tx_fisher_ownerships",
    "tx_scurry_ownerships",
    "tx_taylor_ownerships",
    "tx_throckmorton_ownerships",
    "tx_archer_ownerships",
    "tx_shackelford_ownerships",
    "tx_brown_ownerships",
    "tx_wilbarger_ownerships",
    "tx_knox_ownerships",
    "tx_foard_ownerships",
    "tx_stephens_ownerships",
    "tx_runnels_ownerships",
    "tx_wichita_ownerships",
    "tx_callahan_ownerships",
    "tx_cottle_ownerships",
    "tx_kent_ownerships",
    "tx_haskell_ownerships",
    "tx_jones_ownerships",
    "tx_mitchell_ownerships",
    // "tx_coleman_ownerships", error
    "tx_baylor_ownerships",
    "tx_montague_ownerships",
    "tx_eastland_ownerships",
    "tx_stonewall_ownerships",
    "tx_hardeman_ownerships",
    "tx_jack_ownerships",
    "tx_comanche_ownerships",
    "tx_nolan_ownerships",
    "tx_young_ownerships",
    "tx_clay_ownerships",
  ],
  "Ownerships-Metroplex": [
    "tx_fannin_ownerships",
    "tx_kaufman_ownerships",
    "tx_navarro_ownerships",
    "tx_hood_ownerships",
    "tx_wise_ownerships",
    "tx_somervell_ownerships",
    "tx_parker_ownerships",
    "tx_cooke_ownerships",
    "tx_tarrant_ownerships",
    "tx_rockwall_ownerships",
    "tx_denton_ownerships",
    "tx_palo-pinto_ownerships",
    "tx_hunt_ownerships",
    "tx_collin_ownerships",
    "tx_grayson_ownerships",
    "tx_erath_ownerships",
    "tx_ellis_ownerships",
    "tx_johnson_ownerships",
    "tx_dallas_ownerships",
  ],
  "Ownerships-UpperEast": [
    "tx_rusk_ownerships",
    "tx_titus_ownerships",
    "tx_cass_ownerships",
    "tx_harrison_ownerships",
    "tx_smith_ownerships",
    "tx_red-river_ownerships",
    "tx_wood_ownerships",
    "tx_delta_ownerships",
    "tx_rains_ownerships",
    "tx_camp_ownerships",
    "tx_lamar_ownerships",
    "tx_anderson_ownerships",
    "tx_upshur_ownerships",
    "tx_bowie_ownerships",
    "tx_henderson_ownerships",
    "tx_marion_ownerships",
    "tx_hopkins_ownerships",
    "tx_gregg_ownerships",
    "tx_franklin_ownerships",
    "tx_morris_ownerships",
    "tx_van-zandt_ownerships",
    "tx_panola_ownerships",
    "tx_cherokee_ownerships",
  ],
  "Ownerships-SouthEast": [
    "tx_orange_ownerships",
    "tx_trinity_ownerships",
    "tx_san-jacinto_ownerships",
    "tx_jasper_ownerships",
    "tx_tyler_ownerships",
    "tx_angelina_ownerships",
    "tx_hardin_ownerships",
    "tx_newton_ownerships",
    "tx_sabine_ownerships",
    "tx_shelby_ownerships",
    "tx_polk_ownerships",
    "tx_houston_ownerships",
    "tx_san-augustine_ownerships",
    "tx_nacogdoches_ownerships",
    "tx_jefferson_ownerships",
  ],
  "Ownerships-GulfCoast": [
    "tx_galveston_ownerships",
    "tx_harris_ownerships",
    "tx_matagorda_ownerships",
    "tx_austin_ownerships",
    "tx_waller_ownerships",
    "tx_chambers_ownerships",
    "tx_montgomery_ownerships",
    "tx_colorado_ownerships",
    "tx_wharton_ownerships",
    "tx_walker_ownerships",
    "tx_brazoria_ownerships",
    "tx_liberty_ownerships",
    "tx_fort-bend_ownerships",
  ],
  "Ownerships-Central": [
    "tx_llano_ownerships",
    "tx_lampasas_ownerships",
    "tx_hamilton_ownerships",
    "tx_washington_ownerships",
    "tx_grimes_ownerships",
    "tx_robertson_ownerships",
    "tx_freestone_ownerships",
    "tx_coryell_ownerships",
    "tx_travis_ownerships",
    "tx_hill_ownerships",
    "tx_burleson_ownerships",
    "tx_caldwell_ownerships",
    "tx_bosque_ownerships",
    "tx_lee_ownerships",
    "tx_san-saba_ownerships",
    "tx_mills_ownerships",
    "tx_hays_ownerships",
    "tx_limestone_ownerships",
    "tx_falls_ownerships",
    "tx_fayette_ownerships",
    "tx_bastrop_ownerships",
    "tx_mclennan_ownerships",
    // "tx_leon_ownerships", error here
    "tx_madison_ownerships",
    "tx_blanco_ownerships",
    "tx_bell_ownerships",
    "tx_milam_ownerships",
    "tx_williamson_ownerships",
    "tx_burnet_ownerships",
    "tx_brazos_ownerships",
  ],
  "Ownerships-Alamo": [
    "tx_gonzales_ownerships",
    "tx_la-salle_ownerships",
    "tx_kinney_ownerships",
    "tx_lavaca_ownerships",
    "tx_bandera_ownerships",
    "tx_calhoun_ownerships",
    "tx_zavala_ownerships",
    "tx_guadalupe_ownerships",
    "tx_dimmit_ownerships",
    "tx_atascosa_ownerships",
    "tx_val-verde_ownerships",
    "tx_gillespie_ownerships",
    "tx_real_ownerships",
    "tx_edwards_ownerships",
    "tx_wilson_ownerships",
    "tx_maverick_ownerships",
    "tx_goliad_ownerships",
    "tx_bexar_ownerships",
    "tx_karnes_ownerships",
    "tx_dewitt_ownerships",
    "tx_jackson_ownerships",
    "tx_uvalde_ownerships",
    // "tx_frio_ownerships", error here
    "tx_kendall_ownerships",
    "tx_comal_ownerships",
    "tx_victoria_ownerships",
    "tx_kerr_ownerships",
    "tx_medina_ownerships",
  ],
  "Ownerships-West": [
    "tx_gaines_ownerships",
    "tx_irion_ownerships",
    "tx_upton_ownerships",
    "tx_winkler_ownerships",
    "tx_howard_ownerships",
    "tx_martin_ownerships",
    "tx_dawson_ownerships",
    "tx_mcculloch_ownerships",
    "tx_coke_ownerships",
    "tx_crane_ownerships",
    "tx_schleicher_ownerships",
    "tx_sterling_ownerships",
    "tx_loving_ownerships",
    "tx_reagan_ownerships",
    "tx_mason_ownerships",
    "tx_ector_ownerships",
    "tx_tom-green_ownerships",
    // "tx_crockett_ownerships", error here
    "tx_reeves_ownerships",
    "tx_kimble_ownerships",
    "tx_pecos_ownerships",
    "tx_borden_ownerships",
    "tx_andrews_ownerships",
    "tx_menard_ownerships",
    "tx_midland_ownerships",
    "tx_terrell_ownerships",
    "tx_glasscock_ownerships",
    "tx_ward_ownerships",
    "tx_sutton_ownerships",
    "tx_concho_ownerships",
  ],
  "Ownerships-RioGrande": [
    "tx_brewster_ownerships",
    "tx_presidio_ownerships",
    "tx_el-paso_ownerships",
    "tx_hudspeth_ownerships",
    "tx_culberson_ownerships",
    "tx_jeff-davis_ownerships",
  ],
  "Ownerships-South": [
    "tx_duval_ownerships",
    "tx_kenedy_ownerships",
    "tx_bee_ownerships",
    "tx_refugio_ownerships",
    "tx_mcmullen_ownerships",
    "tx_webb_ownerships",
    "tx_jim-hogg_ownerships",
    "tx_willacy_ownerships",
    "tx_live-oak_ownerships",
    "tx_brooks_ownerships",
    "tx_nueces_ownerships",
    "tx_zapata_ownerships",
    "tx_san-patricio_ownerships",
    "tx_kleberg_ownerships",
    "tx_starr_ownerships",
    "tx_jim-wells_ownerships",
    "tx_aransas_ownerships",
    "tx_cameron_ownerships",
    "tx_hidalgo_ownerships",
  ],
};

/*---------------
    PARCELS
---------------*/
export const parcelSources = {
  "Parcels-HighPlains": [
    // "tx_donley", error
    "tx_dickens",
    // "tx_garza", error
    "tx_cochran",
    "tx_hansford",
    "tx_crosby",
    "tx_moore",
    "tx_roberts",
    "tx_dallam",
    "tx_lamb",
    "tx_lubbock",
    "tx_potter",
    "tx_motley",
    "tx_floyd",
    "tx_hale",
    "tx_yoakum",
    "tx_castro",
    "tx_carson",
    "tx_parmer",
    "tx_king",
    "tx_bailey",
    "tx_hall",
    "tx_wheeler",
    "tx_collingsworth",
    "tx_sherman",
    "tx_lynn",
    // "tx_armstrong", error
    "tx_childress",
    "tx_deaf-smith",
    "tx_hartley",
    "tx_briscoe",
    "tx_lipscomb",
    "tx_oldham",
    "tx_randall",
    "tx_swisher",
    "tx_gray",
    "tx_hockley",
    // "tx_hutchinson", error
    "tx_terry",
    "tx_hemphill",
    "tx_ochiltree",
    "tx_cochran_less",
    "tx_roberts_less",
    "tx_floyd_less",
    "tx_collingsworth_less",
    "tx_dickens_less",
    "tx_parmer_less",
    "tx_childress_less",
    "tx_moore_less",
    "tx_swisher_less",
    "tx_carson_less",
    "tx_motley_less",
    "tx_lamb_less",
    "tx_crosby_less",
    "tx_yoakum_less",
    "tx_hall_less",
    "tx_hartley_less",
    // "tx_hutchinson_less", error
    "tx_hockley_less",
    "tx_terry_less",
    "tx_lubbock_less",
    "tx_randall_less",
    "tx_hale_less",
    "tx_wheeler_less",
    "tx_king_less",
    // "tx_donley_less", error
    "tx_briscoe_less",
    "tx_gray_less",
    "tx_dallam_less",
    "tx_hemphill_less",
    "tx_oldham_less",
    "tx_ochiltree_less",
    // "tx_garza_less", error
    "tx_armstrong_less",
    "tx_lipscomb_less",
    "tx_bailey_less",
    "tx_lynn_less",
    "tx_deaf-smith_less",
    "tx_sherman_less",
    "tx_potter_less",
    "tx_hansford_less",
    "tx_castro_less",
  ],
  "Parcels-Northwest": [
    "tx_fisher",
    "tx_scurry",
    "tx_taylor",
    "tx_throckmorton",
    // "tx_archer", error
    "tx_shackelford",
    "tx_brown",
    "tx_wilbarger",
    "tx_knox",
    "tx_foard",
    "tx_stephens",
    "tx_runnels",
    "tx_wichita",
    "tx_callahan",
    "tx_cottle",
    "tx_kent",
    "tx_haskell",
    "tx_jones",
    "tx_mitchell",
    // "tx_coleman", error
    "tx_baylor",
    "tx_montague",
    "tx_eastland",
    "tx_stonewall",
    "tx_hardeman",
    "tx_jack",
    "tx_comanche",
    "tx_nolan",
    "tx_young",
    "tx_clay",
    "tx_wichita_less",
    "tx_stonewall_less",
    "tx_taylor_less",
    "tx_knox_less",
    "tx_callahan_less",
    "tx_wilbarger_less",
    "tx_shackelford_less",
    "tx_throckmorton_less",
    "tx_jack_less",
    "tx_hardeman_less",
    "tx_fisher_less",
    "tx_clay_less",
    // "tx_coleman_less", error
    "tx_jones_less",
    "tx_foard_less",
    "tx_cottle_less",
    "tx_archer_less",
    "tx_young_less",
    "tx_comanche_less",
    "tx_baylor_less",
    "tx_kent_less",
    "tx_eastland_less",
    "tx_scurry_less",
    "tx_montague_less",
    "tx_nolan_less",
    "tx_stephens_less",
    "tx_haskell_less",
    "tx_mitchell_less",
    "tx_brown_less",
    "tx_runnels_less",
  ],
  "Parcels-Metroplex": [
    "tx_fannin",
    "tx_kaufman",
    "tx_navarro",
    "tx_hood",
    "tx_wise",
    "tx_somervell",
    "tx_parker",
    "tx_cooke",
    "tx_tarrant",
    "tx_rockwall",
    "tx_denton",
    "tx_palo-pinto",
    "tx_hunt",
    "tx_collin",
    "tx_grayson",
    "tx_erath",
    "tx_ellis",
    "tx_johnson",
    "tx_dallas",
    "tx_wise_less",
    "tx_dallas_less",
    "tx_fannin_less",
    "tx_parker_less",
    "tx_erath_less",
    "tx_cooke_less",
    "tx_palo-pinto_less",
    "tx_navarro_less",
    "tx_grayson_less",
    "tx_ellis_less",
    "tx_hunt_less",
    "tx_johnson_less",
    "tx_somervell_less",
    "tx_denton_less",
    "tx_kaufman_less",
    "tx_rockwall_less",
    "tx_collin_less",
    "tx_hood_less",
    "tx_tarrant_less",
  ],
  "Parcels-UpperEast": [
    "tx_rusk",
    "tx_titus",
    "tx_cass",
    "tx_harrison",
    "tx_smith",
    "tx_red-river",
    "tx_wood",
    "tx_delta",
    "tx_rains",
    "tx_camp",
    "tx_lamar",
    // "tx_anderson", error
    "tx_upshur",
    "tx_bowie",
    "tx_henderson",
    "tx_marion",
    "tx_hopkins",
    "tx_gregg",
    "tx_franklin",
    "tx_morris",
    "tx_van-zandt",
    "tx_panola",
    "tx_cherokee",
    "tx_marion_less",
    "tx_franklin_less",
    "tx_morris_less",
    "tx_gregg_less",
    "tx_rains_less",
    "tx_hopkins_less",
    "tx_titus_less",
    "tx_henderson_less",
    "tx_smith_less",
    "tx_wood_less",
    "tx_panola_less",
    "tx_rusk_less",
    "tx_lamar_less",
    "tx_van-zandt_less",
    "tx_harrison_less",
    "tx_delta_less",
    "tx_red-river_less",
    "tx_cass_less",
    "tx_bowie_less",
    "tx_camp_less",
    "tx_anderson_less",
    "tx_cherokee_less",
    "tx_upshur_less",
  ],
  "Parcels-SouthEast": [
    "tx_orange",
    "tx_trinity",
    "tx_san-jacinto",
    "tx_jasper",
    "tx_tyler",
    // "tx_angelina", error
    "tx_hardin",
    "tx_newton",
    "tx_sabine",
    "tx_shelby",
    "tx_polk",
    "tx_houston",
    "tx_san-augustine",
    "tx_nacogdoches",
    "tx_jefferson",
    "tx_san-jacinto_less",
    "tx_shelby_less",
    "tx_angelina_less",
    "tx_houston_less",
    "tx_jefferson_less",
    "tx_polk_less",
    // "tx_newton_less", error
    "tx_san-augustine_less",
    "tx_hardin_less",
    "tx_sabine_less",
    "tx_nacogdoches_less",
    "tx_tyler_less",
    "tx_orange_less",
    "tx_trinity_less",
    "tx_jasper_less",
  ],
  "Parcels-GulfCoast": [
    "tx_galveston",
    "tx_harris",
    "tx_matagorda",
    // "tx_austin", error
    "tx_waller",
    "tx_chambers",
    "tx_montgomery",
    "tx_colorado",
    "tx_wharton",
    "tx_walker",
    "tx_brazoria",
    "tx_liberty",
    "tx_fort-bend",
    "tx_matagorda_less",
    "tx_colorado_less",
    "tx_walker_less",
    "tx_fort-bend_less",
    "tx_galveston_less",
    "tx_waller_less",
    "tx_liberty_less",
    "tx_austin_less",
    "tx_brazoria_less",
    "tx_wharton_less",
    "tx_chambers_less",
    "tx_harris_less",
    "tx_montgomery_less",
  ],
  "Parcels-Central": [
    "tx_llano",
    "tx_lampasas",
    "tx_hamilton",
    "tx_washington",
    "tx_grimes",
    "tx_robertson",
    "tx_freestone",
    "tx_coryell",
    "tx_travis",
    "tx_hill",
    "tx_burleson",
    "tx_caldwell",
    "tx_bosque",
    "tx_lee",
    "tx_san-saba",
    "tx_mills",
    "tx_hays",
    "tx_limestone",
    "tx_falls",
    "tx_fayette",
    "tx_bastrop",
    "tx_mclennan",
    // "tx_leon", error
    "tx_madison",
    "tx_blanco",
    "tx_bell",
    "tx_milam",
    "tx_williamson",
    "tx_burnet",
    "tx_brazos",
    "tx_williamson_less",
    "tx_fayette_less",
    "tx_travis_less",
    "tx_mills_less",
    "tx_lee_less",
    "tx_falls_less",
    "tx_bell_less",
    "tx_limestone_less",
    "tx_freestone_less",
    "tx_bastrop_less",
    "tx_lampasas_less",
    "tx_coryell_less",
    "tx_bosque_less",
    "tx_san-saba_less",
    "tx_burnet_less",
    "tx_milam_less",
    "tx_brazos_less",
    "tx_caldwell_less",
    "tx_hays_less",
    "tx_robertson_less",
    "tx_blanco_less",
    "tx_hamilton_less",
    "tx_mclennan_less",
    "tx_hill_less",
    "tx_madison_less",
    // "tx_leon_less", error
    "tx_washington_less",
    "tx_burleson_less",
    "tx_llano_less",
    "tx_grimes_less",
    "tx_llano_merged",
    "tx_lampasas_merged",
    "tx_hamilton_merged",
    "tx_washington_merged",
    "tx_grimes_merged",
    "tx_robertson_merged",
    "tx_freestone_merged",
    "tx_coryell_merged",
    "tx_travis_merged",
    "tx_hill_merged",
    "tx_burleson_merged",
    "tx_caldwell_merged",
    "tx_bosque_merged",
    "tx_lee_merged",
    "tx_san-saba_merged",
    "tx_mills_merged",
    "tx_hays_merged",
    "tx_limestone_merged",
    "tx_falls_merged",
    "tx_fayette_merged",
    "tx_bastrop_merged",
    "tx_mclennan_merged",
    // "tx_leon_merged", error
    "tx_madison_merged",
    "tx_blanco_merged",
    "tx_bell_merged",
    "tx_milam_merged",
    "tx_williamson_merged",
    "tx_burnet_merged",
    "tx_brazos_merged",
  ],
  "Parcels-Alamo": [
    "tx_gonzales",
    "tx_la-salle",
    "tx_kinney",
    "tx_lavaca",
    "tx_bandera",
    "tx_calhoun",
    "tx_zavala",
    "tx_guadalupe",
    "tx_dimmit",
    // "tx_atascosa", error
    "tx_val-verde",
    "tx_gillespie",
    "tx_real",
    "tx_edwards",
    "tx_wilson",
    "tx_maverick",
    "tx_goliad",
    "tx_bexar",
    "tx_karnes",
    "tx_dewitt",
    "tx_jackson",
    "tx_uvalde",
    "tx_frio",
    "tx_kendall",
    "tx_comal",
    "tx_victoria",
    "tx_kerr",
    "tx_medina",
    "tx_gillespie_less",
    "tx_kendall_less",
    "tx_maverick_less",
    "tx_bandera_less",
    "tx_wilson_less",
    "tx_calhoun_less",
    "tx_karnes_less",
    "tx_jackson_less",
    "tx_lavaca_less",
    "tx_victoria_less",
    "tx_kinney_less",
    "tx_atascosa_less",
    "tx_medina_less",
    "tx_real_less",
    "tx_la-salle_less",
    "tx_zavala_less",
    "tx_val-verde_less",
    "tx_frio_less",
    "tx_dimmit_less",
    "tx_goliad_less",
    "tx_edwards_less",
    "tx_uvalde_less",
    "tx_comal_less",
    "tx_dewitt_less",
    "tx_guadalupe_less",
    "tx_kerr_less",
    "tx_gonzales_less",
    "tx_bexar_less",
  ],
  "Parcels-West": [
    "tx_gaines",
    "tx_irion",
    "tx_upton",
    "tx_winkler",
    "tx_howard",
    "tx_martin",
    "tx_dawson",
    "tx_mcculloch",
    "tx_coke",
    "tx_crane",
    "tx_schleicher",
    "tx_sterling",
    "tx_loving",
    "tx_reagan",
    "tx_mason",
    "tx_ector",
    "tx_tom-green",
    // "tx_crockett", error
    "tx_reeves",
    "tx_kimble",
    "tx_pecos",
    "tx_borden",
    // "tx_andrews", error
    "tx_menard",
    "tx_midland",
    "tx_terrell",
    "tx_glasscock",
    "tx_ward",
    "tx_sutton",
    "tx_concho",
    "tx_reagan_less",
    "tx_terrell_less",
    "tx_glasscock_less",
    "tx_loving_less",
    "tx_kimble_less",
    // "tx_andrews_less", error
    "tx_reeves_less",
    "tx_howard_less",
    "tx_dawson_less",
    "tx_mcculloch_less",
    "tx_winkler_less",
    "tx_ector_less",
    "tx_borden_less",
    "tx_sterling_less",
    "tx_tom-green_less",
    "tx_upton_less",
    "tx_schleicher_less",
    "tx_crane_less",
    "tx_pecos_less",
    "tx_ward_less",
    "tx_midland_less",
    // "tx_crockett_less", error
    "tx_martin_less",
    "tx_menard_less",
    "tx_sutton_less",
    "tx_gaines_less",
    "tx_concho_less",
    "tx_irion_less",
    "tx_mason_less",
    "tx_coke_less",
  ],
  "Parcels-RioGrande": [
    "tx_brewster",
    "tx_presidio",
    "tx_el-paso",
    "tx_hudspeth",
    "tx_culberson",
    "tx_jeff-davis",
    "tx_jeff-davis_less",
    "tx_culberson_less",
    "tx_brewster_less",
    "tx_hudspeth_less",
    "tx_el-paso_less",
    "tx_presidio_less",
  ],
  "Parcels-South": [
    "tx_duval",
    "tx_kenedy",
    "tx_bee",
    "tx_refugio",
    "tx_mcmullen",
    "tx_webb",
    "tx_jim-hogg",
    "tx_willacy",
    "tx_live-oak",
    "tx_brooks",
    "tx_nueces",
    "tx_zapata",
    "tx_san-patricio",
    "tx_kleberg",
    "tx_starr",
    "tx_jim-wells",
    // "tx_aransas", error
    "tx_cameron",
    "tx_hidalgo",
    "tx_jim-hogg_less",
    "tx_bee_less",
    "tx_kleberg_less",
    "tx_aransas_less",
    "tx_refugio_less",
    "tx_willacy_less",
    "tx_kenedy_less",
    "tx_webb_less",
    "tx_brooks_less",
    "tx_starr_less",
    "tx_live-oak_less",
    "tx_hidalgo_less",
    "tx_mcmullen_less",
    "tx_san-patricio_less",
    "tx_duval_less",
    "tx_nueces_less",
    "tx_cameron_less",
    "tx_jim-wells_less",
    "tx_zapata_less",
  ],
};

/*---------------
    DEFAULT
---------------*/

export const defaultSourcesToLoad = [
  {
    id: "projects_merge",
    type: "vector",
    url: "mapbox://sbarton.projects_merge?optimize=true",
  },
  {
    id: "project_labels_tim",
    type: "vector",
    url: "mapbox://sbarton.project_labels_tim?optimize=true",
  },
  {
    id: "ownerships_merge",
    type: "vector",
    url: "mapbox://sbarton.ownerships_merge?optimize=true",
  },
  {
    id: "govt",
    type: "vector",
    url: "mapbox://sbarton.govt?optimize=true",
  },
  {
    id: "properties",
    type: "vector",
    url: "mapbox://sbarton.properties",
  },
  {
    id: "PCC_inactive",
    type: "vector",
    url: "mapbox://sbarton.PCC_inactive?optimize=true",
  },
  {
    id: "unmatched",
    type: "vector",
    url: "mapbox://sbarton.unmatched",
  },
  {
    id: "home",
    type: "vector",
    url: "mapbox://sbarton.home?optimize=true",
  },
  {
    id: "city",
    type: "vector",
    url: "mapbox://sbarton.city?optimize=true",
  },
  {
    id: "school",
    type: "vector",
    url: "mapbox://sbarton.school?optimize=true",
  },
  {
    id: "ETJ",
    type: "vector",
    url: "mapbox://sbarton.ETJ?optimize=true",
  },
  {
    id: "utilitydistricts_austin",
    type: "vector",
    url: "mapbox://sbarton.utilitydistricts_austin?optimize=true",
  },
  {
    id: "opportunityzonestx",
    type: "vector",
    url: "mapbox://sbarton.opportunityzonestx?optimize=true",
  },
  {
    id: "wells",
    type: "vector",
    url: "mapbox://sbarton.wells",
  },
  {
    id: "og_wells",
    type: "vector",
    url: "mapbox://sbarton.og_wells?optimize=true",
  },
  {
    id: "railroad",
    type: "vector",
    url: "mapbox://sbarton.railroad?optimize=true",
  },
  {
    id: "powerlines",
    type: "vector",
    url: "mapbox://sbarton.powerlines?optimize=true",
  },
  {
    id: "counties",
    type: "vector",
    url: "mapbox://sbarton.ctbvmlve",
  },
  {
    id: "water_merge",
    type: "vector",
    url: "mapbox://sbarton.water_merge?optimize=true",
  },
  {
    id: "waterextent",
    type: "vector",
    url: "mapbox://sbarton.waterextent?optimize=true",
  },
  {
    id: "waste_water_merge",
    type: "vector",
    url: "mapbox://sbarton.waste_water_merge?optimize=true",
  },
  {
    id: "wastewaterextent",
    type: "vector",
    url: "mapbox://sbarton.wastewaterextent?optimize=true",
  },
  {
    id: "waterccn",
    type: "vector",
    url: "mapbox://sbarton.waterccn?optimize=true",
  },
  {
    id: "sewerccn",
    type: "vector",
    url: "mapbox://sbarton.sewerccn?optimize=true",
  },
  {
    id: "mapbox-traffic",
    type: "vector",
    url: "mapbox://mapbox.mapbox-traffic-v1",
  },
  {
    id: "point_Data",
    type: "vector",
    url: "mapbox://sbarton.point_Data?optimize=true",
  },
  {
    id: "nlcd_2004",
    type: "raster",
    url: "mapbox://sbarton.nlcd_2004",
  },
  {
    id: "nlcd_2006",
    type: "raster",
    url: "mapbox://sbarton.nlcd_2006",
  },
  {
    id: "nlcd_2008",
    type: "raster",
    url: "mapbox://sbarton.nlcd_2008",
  },
  {
    id: "nlcd_2011",
    type: "raster",
    url: "mapbox://sbarton.nlcd_2011",
  },
  {
    id: "nlcd_2013",
    type: "raster",
    url: "mapbox://sbarton.nlcd_2013",
  },
  {
    id: "nlcd_2016",
    type: "raster",
    url: "mapbox://sbarton.nlcd_2016",
  },
  {
    id: "nlcd_2019",
    type: "raster",
    url: "mapbox://sbarton.nlcd_2019",
  },

  {
    id: "flood",
    type: "vector",
    url: "mapbox://sbarton.flood",
  },
  {
    id: "fema500yr",
    type: "vector",
    url: "mapbox://sbarton.fema500yr",
  },
  {
    id: "creeks_state",
    type: "vector",
    url: "mapbox://sbarton.creeks_state?optimize=true",
  },
  {
    id: "cwqbz",
    type: "vector",
    url: "mapbox://sbarton.cwqbz?optimize=true",
  },
  {
    id: "contour_elev",
    type: "vector",
    url: "mapbox://sbarton.contour_elev",
  },
  {
    id: "slope",
    type: "raster",
    url: "mapbox://sbarton.slope_more_15",
  },
  {
    id: "pipelines",
    type: "vector",
    url: "mapbox://sbarton.pipelines?optimize=true",
  },
  {
    id: "edwardsrechargezone",
    type: "vector",
    url: "mapbox://sbarton.edwardsrechargezone?optimize=true",
  },
  {
    id: "edwardscontributingzone",
    type: "vector",
    url: "mapbox://sbarton.edwardscontributingzone?optimize=true",
  },
  {
    id: "gcwh",
    type: "vector",
    url: "mapbox://sbarton.gcwh?optimize=true",
  },
  {
    id: "growth",
    type: "vector",
    url: "mapbox://sbarton.growth?optimize=true",
  },
  {
    id: "changes_2004-2006",
    type: "raster",
    url: "mapbox://sbarton.changes_2004-2006",
  },
  {
    id: "changes_2006-2008",
    type: "raster",
    url: "mapbox://sbarton.changes_2006-2008",
  },
  {
    id: "changes_2008-2011",
    type: "raster",
    url: "mapbox://sbarton.changes_2008-2011",
  },
  {
    id: "changes_2011-2013",
    type: "raster",
    url: "mapbox://sbarton.changes_2011-2013",
  },
  {
    id: "changes_2013-2016",
    type: "raster",
    url: "mapbox://sbarton.changes_2013-2016",
  },
  {
    id: "changes_2016-2019",
    type: "raster",
    url: "mapbox://sbarton.changes_2016-2019",
  },
  {
    id: "intermittent_creeks",
    type: "vector",
    url: "mapbox://sbarton.intermittent_creeks",
  },
  {
    id: "perennial",
    type: "vector",
    url: "mapbox://sbarton.perennial",
  },
  {
    id: "waterbody",
    type: "vector",
    url: "mapbox://sbarton.waterbody",
  },
  {
    id: "whiteout",
    type: "raster",
    url: "mapbox://sbarton.whiteout",
  },
];
