export const shareMapPossibleLayers = {
    'Projects':'Projects',
    'PerformingProjects':'Performing Projects',
    'OrigOwner':'Ownerships',
    'Listings':'Listings',
    'Sales':'Sales',
    'Pending':'Pending Sales',
    'Parcels-HighPlains':'Parcels (High Plains)',
    'Parcels-Northwest':'Parcels (Northwest)',
    'Parcels-Metroplex':'Parcles (Metroplex)',
    'Parcels-UpperEast':'Parcels (Upper East)',
    'Parcels-SouthEast':'Parcels (South East)',
    'Parcels-GulfCoast':'Parcels (Gulf Coast)',
    'Parcels-Central':'Parcels (Central)',
    'Parcels-Alamo':'Parcels (Alamo)',
    'Parcels-West':'Parcels (West)',
    'Parcels-RioGrande':'Parcels (Rio Grande)',
    'Parcels-South':'Parcels (South)',
    'Ownerships-HighPlains':'Ownerships (High Plains)',
    'Ownerships-Northwest':'Ownerships (Northwest)',
    'Ownerships-Metroplex':'Ownerships (Metroplex)',
    'Ownerships-UpperEast':'Ownerships (Upper East)',
    'Ownerships-SouthEast':'Ownerships (South East)',
    'Ownerships-GulfCoast':'Ownerships (Gulf Coast)',
    'Ownerships-Central':'Ownerships (Central)',
    'Ownerships-Alamo':'Ownerships (Alamo)',
    'Ownerships-West':'Ownerships (West)',
    'Ownerships-RioGrande':'Ownerships (Rio Grande)',
    'Ownerships-South':'Ownerships (South)',
    'SchoolZones':'School Districts',
    'Cities':'Cities',
    'ETJ': 'ETJ',
    'UtilityDistricts':'Utility Districts',
    'OpportunityZones':'Opportunity Zones',
    'Railroads':'Railroads',
    'PowerLines':'Power Lines',
    'Power Lines':'Power Lines',
    'Counties':'Counties',
    'Water':'Water',
    'WaterExtent':'Water Extent',
    'WasteWater': 'Waste Water',
    'UtilityDistricts':'Utility Districts',
    'WasteWaterExtent':'Waste Water Extent',
    'WaterCCN':'Water CCN',
    'SewerCCN':'Sewer CCN',
    'Unacast':'Migration Inflow',
    'Traffic':'Traffic',
    'Government':'Government',
    'FEMA100yr':'FEMA 100yr',
    'FEMA500yr':'FEMA 500yr',
    'Creeks':'Creeks',
    'CWQ':'CWQ',
    'ContourLines':'Topography',
    'Slope':'Over 15% Slope',
    'Pipelines':'Pipelines',
    'Wells':'Wells',
    'OGWells':'Oil/Gas Wells',
    'EdwardsRecharge':'Edwards Recharge',
    'EdwardsContributing':'Edwards Contributing',
    'GCWH':'GCWH',
    'PCC_inactive':'PCC inactive',
    'HomeSales': 'Home Sales',
    'Perennial':'Perennial',
    'Intermittent':'Intermittent',
    'Waterbody':'Waterbody',
    'Whiteout':'Unusable Land'
}
